version: 2
updates:
  - package-ecosystem: terraform
    directory: aws/s3
    schedule:
      interval: weekly
    commit-message:
      prefix: "fix(deps)"
  - package-ecosystem: terraform
    directory: aws/route53
    schedule:
      interval: weekly
    commit-message:
      prefix: "fix(deps)"
